/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    get: {
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/comments": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          updated_at?: parameters["rowFilter.comments.updated_at"];
          post_id?: parameters["rowFilter.comments.post_id"];
          text?: parameters["rowFilter.comments.text"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["comments"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          updated_at?: parameters["rowFilter.comments.updated_at"];
          post_id?: parameters["rowFilter.comments.post_id"];
          text?: parameters["rowFilter.comments.text"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.comments.id"];
          user_id?: parameters["rowFilter.comments.user_id"];
          created_at?: parameters["rowFilter.comments.created_at"];
          updated_at?: parameters["rowFilter.comments.updated_at"];
          post_id?: parameters["rowFilter.comments.post_id"];
          text?: parameters["rowFilter.comments.text"];
        };
        body: {
          /** comments */
          comments?: definitions["comments"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/favorits": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favorits.id"];
          user_id?: parameters["rowFilter.favorits.user_id"];
          created_at?: parameters["rowFilter.favorits.created_at"];
          updated_at?: parameters["rowFilter.favorits.updated_at"];
          post_id?: parameters["rowFilter.favorits.post_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["favorits"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** favorits */
          favorits?: definitions["favorits"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favorits.id"];
          user_id?: parameters["rowFilter.favorits.user_id"];
          created_at?: parameters["rowFilter.favorits.created_at"];
          updated_at?: parameters["rowFilter.favorits.updated_at"];
          post_id?: parameters["rowFilter.favorits.post_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.favorits.id"];
          user_id?: parameters["rowFilter.favorits.user_id"];
          created_at?: parameters["rowFilter.favorits.created_at"];
          updated_at?: parameters["rowFilter.favorits.updated_at"];
          post_id?: parameters["rowFilter.favorits.post_id"];
        };
        body: {
          /** favorits */
          favorits?: definitions["favorits"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/likes": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          user_id?: parameters["rowFilter.likes.user_id"];
          created_at?: parameters["rowFilter.likes.created_at"];
          updated_at?: parameters["rowFilter.likes.updated_at"];
          post_id?: parameters["rowFilter.likes.post_id"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["likes"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** likes */
          likes?: definitions["likes"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          user_id?: parameters["rowFilter.likes.user_id"];
          created_at?: parameters["rowFilter.likes.created_at"];
          updated_at?: parameters["rowFilter.likes.updated_at"];
          post_id?: parameters["rowFilter.likes.post_id"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.likes.id"];
          user_id?: parameters["rowFilter.likes.user_id"];
          created_at?: parameters["rowFilter.likes.created_at"];
          updated_at?: parameters["rowFilter.likes.updated_at"];
          post_id?: parameters["rowFilter.likes.post_id"];
        };
        body: {
          /** likes */
          likes?: definitions["likes"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/posts": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          user_id?: parameters["rowFilter.posts.user_id"];
          created_at?: parameters["rowFilter.posts.created_at"];
          updated_at?: parameters["rowFilter.posts.updated_at"];
          text?: parameters["rowFilter.posts.text"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["posts"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** posts */
          posts?: definitions["posts"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          user_id?: parameters["rowFilter.posts.user_id"];
          created_at?: parameters["rowFilter.posts.created_at"];
          updated_at?: parameters["rowFilter.posts.updated_at"];
          text?: parameters["rowFilter.posts.text"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.posts.id"];
          user_id?: parameters["rowFilter.posts.user_id"];
          created_at?: parameters["rowFilter.posts.created_at"];
          updated_at?: parameters["rowFilter.posts.updated_at"];
          text?: parameters["rowFilter.posts.text"];
        };
        body: {
          /** posts */
          posts?: definitions["posts"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/profiles": {
    get: {
      parameters: {
        query: {
          user_id?: parameters["rowFilter.profiles.user_id"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
          wedding_hall?: parameters["rowFilter.profiles.wedding_hall"];
          description?: parameters["rowFilter.profiles.description"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["profiles"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          user_id?: parameters["rowFilter.profiles.user_id"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
          wedding_hall?: parameters["rowFilter.profiles.wedding_hall"];
          description?: parameters["rowFilter.profiles.description"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          user_id?: parameters["rowFilter.profiles.user_id"];
          created_at?: parameters["rowFilter.profiles.created_at"];
          updated_at?: parameters["rowFilter.profiles.updated_at"];
          name?: parameters["rowFilter.profiles.name"];
          avatar?: parameters["rowFilter.profiles.avatar"];
          wedding_hall?: parameters["rowFilter.profiles.wedding_hall"];
          description?: parameters["rowFilter.profiles.description"];
        };
        body: {
          /** profiles */
          profiles?: definitions["profiles"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/todos": {
    get: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          created_at?: parameters["rowFilter.todos.created_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          group_id?: parameters["rowFilter.todos.group_id"];
          todo?: parameters["rowFilter.todos.todo"];
          is_done?: parameters["rowFilter.todos.is_done"];
          /** Filtering Columns */
          select?: parameters["select"];
          /** Ordering */
          order?: parameters["order"];
          /** Limiting and Pagination */
          offset?: parameters["offset"];
          /** Limiting and Pagination */
          limit?: parameters["limit"];
        };
        header: {
          /** Limiting and Pagination */
          Range?: parameters["range"];
          /** Limiting and Pagination */
          "Range-Unit"?: parameters["rangeUnit"];
          /** Preference */
          Prefer?: parameters["preferCount"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["todos"][];
        };
        /** Partial Content */
        206: unknown;
      };
    };
    post: {
      parameters: {
        body: {
          /** todos */
          todos?: definitions["todos"];
        };
        query: {
          /** Filtering Columns */
          select?: parameters["select"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** Created */
        201: unknown;
      };
    };
    delete: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          created_at?: parameters["rowFilter.todos.created_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          group_id?: parameters["rowFilter.todos.group_id"];
          todo?: parameters["rowFilter.todos.todo"];
          is_done?: parameters["rowFilter.todos.is_done"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
    patch: {
      parameters: {
        query: {
          id?: parameters["rowFilter.todos.id"];
          user_id?: parameters["rowFilter.todos.user_id"];
          created_at?: parameters["rowFilter.todos.created_at"];
          updated_at?: parameters["rowFilter.todos.updated_at"];
          group_id?: parameters["rowFilter.todos.group_id"];
          todo?: parameters["rowFilter.todos.todo"];
          is_done?: parameters["rowFilter.todos.is_done"];
        };
        body: {
          /** todos */
          todos?: definitions["todos"];
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferReturn"];
        };
      };
      responses: {
        /** No Content */
        204: never;
      };
    };
  };
  "/rpc/handle_new_user": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
  "/rpc/copy_to_profiles_table": {
    post: {
      parameters: {
        body: {
          args: { [key: string]: unknown };
        };
        header: {
          /** Preference */
          Prefer?: parameters["preferParams"];
        };
      };
      responses: {
        /** OK */
        200: unknown;
      };
    };
  };
}

export interface definitions {
  comments: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.user_id`.<fk table='profiles' column='user_id'/>
     */
    user_id?: string;
    created_at: string;
    updated_at: string;
    /**
     * Note:
     * This is a Foreign Key to `posts.id`.<fk table='posts' column='id'/>
     */
    post_id: string;
    text: string;
  };
  favorits: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.user_id`.<fk table='profiles' column='user_id'/>
     */
    user_id?: string;
    created_at: string;
    updated_at: string;
    /**
     * Note:
     * This is a Foreign Key to `posts.id`.<fk table='posts' column='id'/>
     */
    post_id: string;
  };
  likes: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.user_id`.<fk table='profiles' column='user_id'/>
     */
    user_id?: string;
    created_at: string;
    updated_at: string;
    /**
     * Note:
     * This is a Foreign Key to `posts.id`.<fk table='posts' column='id'/>
     */
    post_id: string;
  };
  posts: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string;
    /**
     * Note:
     * This is a Foreign Key to `profiles.user_id`.<fk table='profiles' column='user_id'/>
     */
    user_id?: string;
    created_at: string;
    updated_at: string;
    text: string;
  };
  profiles: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    user_id: string;
    created_at: string;
    updated_at: string;
    name?: string;
    avatar?: string;
    wedding_hall?: string;
    description?: string;
  };
  todos: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: number;
    /**
     * Note:
     * This is a Foreign Key to `profiles.user_id`.<fk table='profiles' column='user_id'/>
     */
    user_id?: string;
    created_at: string;
    updated_at: string;
    group_id?: number;
    todo: string;
    is_done?: boolean;
  };
}

export interface parameters {
  /** Preference */
  preferParams: "params=single-object";
  /** Preference */
  preferReturn: "return=representation" | "return=minimal" | "return=none";
  /** Preference */
  preferCount: "count=none";
  /** Filtering Columns */
  select: string;
  /** On Conflict */
  on_conflict: string;
  /** Ordering */
  order: string;
  /** Limiting and Pagination */
  range: string;
  /** Limiting and Pagination */
  rangeUnit: string;
  /** Limiting and Pagination */
  offset: string;
  /** Limiting and Pagination */
  limit: string;
  /** comments */
  "body.comments": definitions["comments"];
  "rowFilter.comments.id": string;
  "rowFilter.comments.user_id": string;
  "rowFilter.comments.created_at": string;
  "rowFilter.comments.updated_at": string;
  "rowFilter.comments.post_id": string;
  "rowFilter.comments.text": string;
  /** favorits */
  "body.favorits": definitions["favorits"];
  "rowFilter.favorits.id": string;
  "rowFilter.favorits.user_id": string;
  "rowFilter.favorits.created_at": string;
  "rowFilter.favorits.updated_at": string;
  "rowFilter.favorits.post_id": string;
  /** likes */
  "body.likes": definitions["likes"];
  "rowFilter.likes.id": string;
  "rowFilter.likes.user_id": string;
  "rowFilter.likes.created_at": string;
  "rowFilter.likes.updated_at": string;
  "rowFilter.likes.post_id": string;
  /** posts */
  "body.posts": definitions["posts"];
  "rowFilter.posts.id": string;
  "rowFilter.posts.user_id": string;
  "rowFilter.posts.created_at": string;
  "rowFilter.posts.updated_at": string;
  "rowFilter.posts.text": string;
  /** profiles */
  "body.profiles": definitions["profiles"];
  "rowFilter.profiles.user_id": string;
  "rowFilter.profiles.created_at": string;
  "rowFilter.profiles.updated_at": string;
  "rowFilter.profiles.name": string;
  "rowFilter.profiles.avatar": string;
  "rowFilter.profiles.wedding_hall": string;
  "rowFilter.profiles.description": string;
  /** todos */
  "body.todos": definitions["todos"];
  "rowFilter.todos.id": string;
  "rowFilter.todos.user_id": string;
  "rowFilter.todos.created_at": string;
  "rowFilter.todos.updated_at": string;
  "rowFilter.todos.group_id": string;
  "rowFilter.todos.todo": string;
  "rowFilter.todos.is_done": string;
}

export interface operations {}

export interface external {}
